### ISSUE TITLE
Unused Indexes

### ISSUE THREAD

**Issue by joekur** [ankane/pghero#104]
Looking through this repo's history, it looks like the UI for unused indexes was removed in 1.2.1: https://github.com/ankane/pghero/commit/bfc6affbc6e6b0e2994e6aec304964a7ce050755

Just curious why this was considered "noise", as I happen to be in the process of combing through unused indexes for an application. I also notice that the homepage still appears to be running that query: https://github.com/ankane/pghero/blob/19810f25fcdb26f17e868312e457ffef77cf9160/app/controllers/pg_hero/home_controller.rb#L29

I'm not missing a configuration that would enable some UI to view this query, am I? Is that anything that would be considered?

**Comment by PikachuEXE** [comment]
I want the same thing too...
Got duplicate indexes in overview
but not sure which one to be remove...

**Comment by ankane** [comment]
Hey @joekur, I've added unused indexes back behind the `?extended=t` query parameter. From my experience, you really don't need to worry about them. Thanks for pointing out it was still doing that query.

@PikachuEXE, you should remove the index PgHero suggests, as one index typically "covers" the other.

**Comment by rderoldan1** [comment]
@ankane Should suggested indexes be present in the UI?

**Comment by andyatkinson** [comment]
@ankane Digging up an old one here so bear with me 😁 

> From my experience, you really don't need to worry about them. Thanks for pointing out it was still doing that query.

Cybertec suggests removing unused indexes. I started doing this on our primary application and we had > 100 of them and some of them were nearly as large as our largest tables on disk. So, at a minimum it's a way to reduce a lot of disk space usage for an unused index. And there is some impact to write rate. In any case we've been trying to remove them.

https://www.cybertec-postgresql.com/en/get-rid-of-your-unused-indexes/

I thought pghero was missing unused indexes, but found it, then realized it is hidden behind the `extended` param. Is that still a default you prefer to have given it's been a few years? Is there any reason you envision to not have that be the default? I might change our version to make that the default so that we have easier visibility on unused indexes as they might pop in over time.

Thanks!
