### ISSUE TITLE
[Idea] Track max query time or standard deviation

### ISSUE THREAD

**Issue by ellamosi** [ankane/pghero#196]
In our system we have a situation in which certain query frequently runs really fast but occasionally is several orders of magnitude slower. In that situation, the average time metric is not truly representative of the performance implications of a query.

Tracking either the maximum query time or standard deviation per time interval would reveal a bigger picture (in addition to the average time, of course).

Although I'm not familiar with the PGHero source yet, I could take a stab at it if the feature is deemed reasonably useful.

**Comment by ankane** [comment]
Hey @ellamosi, this is an interesting idea. I don't have a great sense of how useful it'll be in practice, but maybe we can make it an option to try it out. Are you thinking of adding it to the Queries tab?

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest AND someone wants to add this, please reply and we can continue to discussion.

**Comment by ibrahima** [comment]
I think this could be very useful for tracking down pathological cases, not sure whether the data to present this is already logged somewhere or not but I think it would be useful for me. Lately I've been trying to track down some database queries that cause request timeouts on really large data sets, and I just came across [your guide on timeouts](https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts). I want to add a database connection timeout setting and I'd find it useful to know what's say, the 90th percentile of database queries so that I can set a conservative timeout initially that doesn't break requests that aren't currently broken (e.g. perhaps one really slow request is okay if it's the only slow request).

If I get a chance I'll poke around to see how feasible this is for me to do!
