### ISSUE TITLE
Integrate with rails 6 multi-databases

### ISSUE THREAD

**Issue by a666** [ankane/pghero#279]
Hi,
we are using mostly Rails as our database management system and with Rails 6 new multi-database support (https://edgeguides.rubyonrails.org/active_record_multiple_databases.html) things are going pretty well.

We believe that it would be ideal for pghero to be able to read the full database config of rails and connect to the defined databases. 

Right now we have to duplicate a lot of our extensive database config (`database.yml`) into the pghero config (`pghero.yml`), which is slightly error prone and not very DRY.

**Comment by ankane** [comment]
Hey @a666, makes sense to me. Feel free to submit a PR.

**Comment by ankane** [comment]
Added support for multiple database when no config is specified. Can probably add another option like `spec` instead of `url` to use the specification from `database.yml` for cases where a config file is present.

**Comment by ankane** [comment]
Added a `spec` option for now, so you can do:

```yml
databases:
  primary:
    spec: primary
```

May rename it before the release. Let me know if you have any suggestions.

Another option would be to automatically resolve it from the database key when possible (so `spec` isn't needed), but that could be considered a breaking change since the current behavior would resolve it to the default connection. May have it do that in the next major release.

**Comment by a666** [comment]
I just tested master and pinged the db team. 

Looks good and works good.

About `spec`, other options could be `config` or `name`. Makes me remember about the two hard things in computer science.

**Comment by ankane** [comment]
Ha, definitely true. Thanks for testing and the name suggestions. Will make a decision before the next release.
