### ISSUE TITLE
[Idea] Improve suggested migrations

### ISSUE THREAD

**Issue by lacostenycoder** [ankane/pghero#282]
When using the suggested migrations, there can be problems adding these to multiple environments i.e. test, staging, production.  I would suggest to migrations to be idempotent and reversible.  I ended up with migrations that look more like this:

```
class CleanupIndices < ActiveRecord::Migration
  def up
    commit_db_transaction do
      add_index :assessment_patients, [:assessable_id], algorithm: :concurrently unless index_exists?(:assessment_patients, :assessable_id )
    end
  end

  def down
    commit_db_transaction do
      remove_index :assessment_patients, [:assessable_id], algorithm: :concurrently if index_exists?(:assessment_patients, :assessable_id )
    end
  end
end
```

**Comment by ankane** [comment]
Hey @lacostenycoder, thanks for the suggestion! Unfortunately, there's not really a way to make concurrent migrations idempotent with the Active Record syntax. With the approach above, a migration can be interrupted during index creation. If the migration is run again, it'll complete successfully since the index exists, but the index will be invalid, which can be dangerous since it looks like the migration succeeded. I think it's better for the migration to fail in this situation.

I think the ideal workflow would be to check if the index exists and is valid, and if it's not valid, delete it and try again, but I'm not sure there's a built-in Active Record method for this (I may try to add a helper in [Strong Migrations](https://github.com/ankane/strong_migrations) for this, but we wouldn't be able to use it for PgHero).

**Comment by lacostenycoder** [comment]
Ok that makes sense, thanks.   I'll keep an eye on Strong Migrations.
