### ISSUE TITLE
[Idea] PostGIS support

### ISSUE THREAD

**Issue by maheshm** [ankane/pghero#283]
I am not sure if this is within the purview of this project, but I would love to see and support the project in adding support for PostGIS. Let me know if you have some ideas in this direction.

**Comment by ankane** [comment]
Hey @maheshm, can you explain a bit more? Are you running into an error when the PostGIS extension is enabled?

**Comment by maheshm** [comment]
No, it works perfectly fine with the extension. But what I would like to have is index suggestions and/or slow query analysis (etc) specific to spacial queries.

**Comment by ankane** [comment]
Thanks for expanding.

Re slow queries: If queries are captured by pg_stat_statements, they'll show up automatically (I imagine this is the case). Otherwise, there's not much PgHero can do.

Re index suggestions: Index suggestions are pretty basic right now, but happy to expand them if you'd like to create a PR.
