### ISSUE TITLE
[Idea] Suggest potentially unused tables and useless columns

### ISSUE THREAD

**Issue by fatkodima** [ankane/pghero#298]
pghero already has suggestions about unused indexes, so it should be helpful to have the same for tables and columns. Unfortunately, it is not easy to make similar for views.

We can not for sure tell if some table/column is unused or not without manual app code investigation, but we can make some assumptions.

For tables we can check:
1. if it is empty
2. when it was last accessed

For columns:
1. if column have only one distinct value or only NULLs, than it seems useless

**Comment by ankane** [comment]
Hey @fatkodima, thanks for the suggestions.

We could give unused tables the same treatment as unused indexes on the space page. There's currently an `unused_tables` method to find tables that haven't been accessed since stats were last reset, but it looks like the query isn't correct at the moment (only checks index scans when it needs to check many other fields in `pg_stat_user_tables`).

Empty tables shouldn't really be a problem for space or the database, and I think a column check could be very expensive.

**Comment by fatkodima** [comment]
> Empty tables shouldn't really be a problem for space or the database

Sure. It only complicates db schema, for newcomers/developers. Would be great to get rid of that.

> I think a column check could be very expensive.

Ah, yes, for columns it needs full scan. I was sure there is a better way using some internal pg data. Initially, I've seen https://wiki.postgresql.org/wiki/Finding_useless_columns , but that uses planner *estimates*.

**Comment by ankane** [comment]
Re empty tables: I imagine they'll be unused if they're really not needed most of the time, which the access check will cover. I don't think it's worth an extra check.

Re columns: Happy to have an `unneeded_columns` method in Ruby with that query, but don't think it's worth adding to the dashboard at this point.

**Comment by ankane** [comment]
Cleaning up issues
