### ISSUE TITLE
PG hero does not work well with sprockets disabled.

### ISSUE THREAD

**Issue by ramaboo** [ankane/pghero#319]
There was clearly some thought given to this here: 

https://github.com/ankane/pghero/blob/0714d085655928e2051c3eff8bcf30af3ca378e1/lib/pghero/engine.rb#L18

However this does not appear to work 100%. It allows the /pghero to run in a rails app without sprockets but none of the stylesheets get loaded so it's hard to use. That if needs some sort of else clause to handle assets when sprockets is not present.

**Comment by ankane** [comment]
Hey @ramaboo, the dashboard requires Sprockets (it's not an explicit dependency since you can use PgHero without the dashboard). If a lot of people run into this issue, we could also add a check for it similar to the one for Rails API: https://github.com/ankane/pghero/blob/1897f7886401ae50fa2c00280fb5f0b7319a2e72/app/controllers/pg_hero/home_controller.rb#L447

**Comment by MrJoy** [comment]
Is there any chance of PgHero being updated to support Webpacker, or the new mechanism Rails 7 provides?
