### ISSUE TITLE
Question around EXPLAIN

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#322]
Does `EXPLAIN ANALYZE` apply changes on the table? 

For example: if I run a delete on a DB does that directly apply on the DB? if so we are looking for a way where we can restrict. people doing so.

Can you share your thoughts?

I was reading through this documentation which does say that it applies on the DB. The below statement confused me a bit 

`If you wish to use EXPLAIN ANALYZE on an INSERT, UPDATE, DELETE, CREATE TABLE AS, or EXECUTE statement without letting the command affect your data, use this approach`

**Comment by ankane** [comment]
Hey @bheemreddy181, `EXPLAIN ANALYZE` will apply changes, so PgHero runs it in a transaction and rollbacks so the changes aren't committed.

**Comment by bheemreddy181** [comment]
Makes sense thanks

**Comment by bheemreddy181** [comment]
After discussion with our DBA’s I could see there is a potential risk with these transactions which could block the application behind the scene when we write UPDATE queries. Your thoughts on the same ? @ankane

**Comment by ankane** [comment]
Hey @bheemreddy181, do you have an example?

It's possible to execute any query that works with `EXPLAIN ANALYZE`, but I haven't seen this cause issues in practice (I imagine most of the queries that are run are ones that the app is already running). Based on https://github.com/ankane/pghero/issues/318#issuecomment-653417274, you might consider forking the gem and adapting it to your needs.

**Comment by bheemreddy181** [comment]
Here is one example from our discussion 

```
UPDATE loans set updated_at = now()
would block all other concurrent writes to the table. It might take 2 minutes to execute
thus locking up the app for 2 minutes
even if it rolls back
```

**Comment by ankane** [comment]
There's a configurable statement timeout (10 seconds by default) that should prevent those situations.

**Comment by jfinzel** [comment]
@ankane allowing arbitrary write SQL to be executed on a production database is never good practice.  As a DBA, I frequently have to debug production query issues.  I have never, ever run EXPLAIN ANALYZE on production, even rolling it back.  That is because a lot can still go wrong.

It underestimates the complexity of what is involved.  Consider high concurrency applications that have an SLA of 10ms response time for a single row update.  You could easily run an explain analyze query that locks a row for update which the application needs to access immediately, thereby blocking the application.  You could even create a deadlock by way of a process and order of operations that is unexpected in the application workflow.

It's not sufficient to try to cover all scenarios via config settings.  10 seconds may work for some queries, but it obviously doesn't work for the high concurrency case above where even 1 second could cause timeouts.  And clearly it would not be realistic to set a global 10ms statement timeout.

Another issue is unintended interference with the application behavior.  Consider if I have the following table foo which has a sequence.  If I run:
```
BEGIN;
EXPLAIN ANALYZE
INSERT INTO foo
SELECT 1;
ROLLBACK;
```

I have actually bumped the sequence by one value.  That may not be deemed significant.  But it's the kind of thing I would never dare to do as a DBA, as it's clearly interfering with what should be application-only traffic.  I have now messed up my app's pretty sequential numbers :).

All this said, there is one last but significant problem.  I have to trust your code will do what it says forever.  That is, I have to trust your app will always run `BEGIN` `ROLLBACK` and not actually commit the transaction.  It is a logical, rather than an absolute, constraint.  With something this important, it is much safer to totally restrict write access.

The `EXPLAIN` feature is good.  But the `EXPLAIN ANALYZE` feature is a definite anti-pattern in wise database administration, and should be optional.  It's the biggest red flag for pghero in terms of the safety.

**Comment by ankane** [comment]
Hey @jfinzel, I appreciate the feedback.

One easy change to make is to allow `explain_timeout_sec` to be a float so it can be set to < 1 sec (it uses a local statement timeout so other queries aren't affected). I don't think the sequence issue is a problem for a majority of applications, and you also have to trust the code to disable `ANALYZE` works, so not sure there's much difference there.

If there's enough demand over time for an option to disable analyze, I'm happy to revisit it, but I'd recommend forking the project for now if you need this.

**Comment by bheemreddy181** [comment]
Thanks for the inputs on this @ankane

**Comment by ankane** [comment]
np, fwiw, there's a test case for explain analyze that should catch regressions. https://github.com/ankane/pghero/blob/5c13d3cb3725f2f3ca7626b1405ffc32b865b34e/test/basic_test.rb#L8-L12

**Comment by bheemreddy181** [comment]
Thanks again
