### ISSUE TITLE
 pghero is suitable for Multitenancy?

### ISSUE THREAD

**Issue by davidvazteixeira** [ankane/pghero#448]
We had success using PgHero in a single schema application and decided to install it in another larger multi-tenancy application. We follow the "Rails guide" install.

The problem is the same as this issue,

* https://github.com/ankane/pghero/issues/144

but it's worse: we have more than **1500 schemes**.

## Under development

* pghero (3.2.0)
* A reduced production dump with only 3 schemas produces 1729 lines in /pghero/space. but no time out
* In production, we estimate it will increase to nearly one million.

## In production

* pghero (3.2.0)
* CPU and memory spikes!
* /pghero -> 502 (timeout)
* ![image](https://user-images.githubusercontent.com/5951270/225410487-b1869f4a-caa6-4f2d-8895-746d94d9e104.png)
* ![image](https://user-images.githubusercontent.com/5951270/225410587-f26eb63f-f3b5-4990-b6b7-1407d5eb0248.png)

## Questions

* Is this an expected situation?
* The problem can be mitigated?
* Is pghero suitable for this use?

**Comment by ankane** [comment]
Hey @davidvazteixeira, PgHero isn't designed to handle a very large number of tables/indexes, so you'll probably need to use a different tool.

I think the three pages that would likely need updated are:

1. Overview - some check would need to be moved to background jobs (and would no longer be real-time)
2. Space - limit to largest tables
3. Maintenance - probably need to paginate

However, since most apps won't need this, I don't think it's worth the extra complexity right now.
