### ISSUE TITLE
The index migration needs to mention `disable_ddl_transaction!`

### ISSUE THREAD

**Issue by sudhirj** [ankane/pghero#58]
Trying to create a index concurrently in Rails need the migration transaction to be disabled. Need to mention that. 

https://robots.thoughtbot.com/how-to-create-postgres-indexes-concurrently-in

Also, GIST indexes can easily be defined int the Rails format itself. Can update that too.

I'll submit a PR for both changes, just putting them down here so I don't forget.

**Comment by ankane** [comment]
Hey @sudhirj, good point about the transaction. I prefer adding:

```ruby
commit_db_transaction
add_index ...
```

instead, as I find it easier to say "put all of this in your change method" rather than "put this outside the change method and this other code inside of it".

If there's a better way to define GIST indexes, happy to switch to that as well.  If this way only works with newer versions of Rails, we should probably conditionally show it.
